"save",
"9 dict dup begin",
"	/FontType 3 def",
"	/FontMatrix [1 33 div 0 0 1 33 div 0 0] def",
"",
"	/Encoding 64 array def 0 1 63 {Encoding exch dup charname put} for",
"	/BuildChar {10 dict begin BuildHershey end} def",
"",
"	/CharData 64 dict def CharData begin",
