"%!PS-Adobe-1.0",
"%%Title: Hershey Font Sample Pages",
"%%Creator: Program by Guy Riddle <ggr@BTL.CSNET>",
"%%Pages: (atend)",
"%%EndComments",
"",
"/inch {72 mul} def",
"/xdef {exch def} def",
"",
"/HersheyPage {",
"	1 sub /maxchar xdef",
"",
"	30 scalefont /font-h xdef",
"",
"	0 1 maxchar {",
"		/charnum xdef",
"",
"		gsave",
"		charnum hplace",
"		font-h /CharData get charnum charname get /chardata xdef",
"",
"		font-c setfont",
"		.3 inch .1 inch moveto",
"		chardata 0 get (????) cvs show",
"",
"		.3 inch .2 inch moveto .3 inch .8 inch lineto",
"		.2 inch .3 inch moveto .8 inch .3 inch lineto",
"		0 setlinewidth stroke",
"",
"		font-h setfont",
"		.3 inch .3 inch moveto",
"		(?) dup 0 charnum put show",
"",
"		grestore",
"	} for",
"",
"	font-r setfont",
"	.5 inch .9 inch moveto",
"	(Size 12: ) show",
"",
"	/Hershey findfont 12 scalefont setfont",
"	all-64 0 maxchar 1 add getinterval show",
"",
"	showpage",
"	restore",
"} def",
"",
"/charname {",
"	(???) cvs cvn",
"} def",
"",
"/hplace {",
"	dup",
"	8 mod /xc xdef",
"	8 idiv /yc xdef",
"",
"	xc 0.45 add inch",
"	7 yc sub 2.00 add inch translate",
"} def",
"",
"/BuildHershey {",
"	/charcode xdef",
"	/CharData get charcode charname get /cd xdef",
"",
"	cd 2 get cd 1 get sub 0 -10 -20 50 60 setcachedevice",
"",
"	/domove true def",
"	/isx true def",
"",
"	cd 3 get {",
"		isx {",
"			dup 32 eq {",
"				pop",
"				/domove true def",
"			} {",
"				82 sub cd 1 get sub",
"				/isx false def",
"			} ifelse",
"		} {",
"			neg 91 add",
"			domove {",
"				moveto",
"				/domove false def",
"			} {",
"				lineto",
"			} ifelse",
"",
"			/isx true def",
"		} ifelse",
"	} forall",
"",
"	1 setmiterlimit 1 setlinejoin 1 setlinecap 1 setlinewidth stroke",
"} def",
"",
"/Courier findfont 7 scalefont /font-c xdef",
"/Times-Roman findfont 12 scalefont /font-r xdef",
"",
"64 string dup 0 1 63 {dup put dup} for pop /all-64 xdef",
"",
"%%EndProlog",
