#!/bin/sh
MYPRINTER=$LASER
DIR="`dirname $0`"
TMP=/tmp/splunge$$
PROG="`basename $0`"
USAGE="$PROG: usage: $PROG [ -help ] [ -Pprinter ] fontfile(s).Z"

while [ $# -gt 0 ]
do
	case $1 in
	-P*)	MYPRINTER=`echo $1 | sed 's/-P//'`;;
	-*)	echo $USAGE 1>&2
		exit 1;;
	*)	break;;
	esac
	shift
done


if [ $# -lt 1 ]
then    echo $USAGE 1>&2; exit 1
fi

for i
do
	echo $MYPRINTER
	echo $i
	zcat $i > $TMP
	$DIR/download -P$MYPRINTER `awk '$1 ~ "FontName" { print substr($2,2); exit }' $TMP` $TMP
done

rm /tmp/splunge$$
