#!/bin/sh

for i in `ls -tr [0-9] [0-9][0-9] [0-9][0-9][0-9] 2>/dev/null`
do
	echo -n "$i -> "
	NAME=`head -1 $i | awk '{ printf "%s", substr($1,1,10) }'`
	NAME=`echo $NAME | tr [A-Z] [a-z]`
	FILE=$NAME.sc
	echo $FILE
	mv -i $i $FILE
done
